//
//  IndicatorSettingViewModel+Enum.m
//  IndicatorSettingsTest
//
//  Created by Kwan Hyun Son on 10/27/23.
//

#import "IndicatorSettingViewModel+Enum.h"

// MARK: - Main Category

NSArray <NSString *>* AllCasesIndiSetMainCategory(void) {
    return @[IndiSetMainCategoryIndicators,
             IndiSetMainCategorySignals,
             IndiSetMainCategoryPatterns,
             IndiSetMainCategoryRanges,
             IndiSetMainCategoryFill,
             IndiSetMainCategoryFavorites];
}

// MARK: - Sub Category

NSArray <NSString *>* AllCasesIndiSetSubCategoryIndica(void) {
    return @[IndiSetSubCategoryIndicaPrice,
             IndiSetSubCategoryIndicaMomentum,
             IndiSetSubCategoryIndicaVolatility,
             IndiSetSubCategoryIndicaChannel,
             IndiSetSubCategoryIndicaTrend,
             IndiSetSubCategoryIndicaMarketStrength,
             IndiSetSubCategoryIndicaVolume,
             IndiSetSubCategoryIndicaOther,
             IndiSetSubCategoryIndicaInvestor];
}

NSArray <NSString *>* AllCasesIndiSetSubCategorySignals(void) {
    return @[IndiSetSubCategorySignalsAnalysis,
             IndiSetSubCategorySignalsTrading];
}


NSArray <NSString *>* AllCasesIndiSetSubCategoryPatterns(void) {
    return @[IndiSetSubCategoryPatternsBullRev,
             IndiSetSubCategoryPatternsBullCont,
             IndiSetSubCategoryPatternsBearRev,
             IndiSetSubCategoryPatternsBearCont,
             IndiSetSubCategoryPatternsSideways,
             IndiSetSubCategoryPatternsBoxTrend,
             IndiSetSubCategoryPatternsTrend];
}

NSArray <NSString *>* AllCasesIndiSetSubCategoryFill(void) {
    return @[IndiSetSubCategoryFillPriceRange,
             IndiSetSubCategoryFillVolumeRange,
             IndiSetSubCategoryFillAnalysisRange];
}


// MARK: - Detail Category: 현재 609개

/// 지표 - 가격지표 30개
NSArray <NSString *>* AllCasesIndiSetDeCateIndicaPrice(void) {
    return @[IndiSetDeCateIndicaPriceBollingerBands,
             IndiSetDeCateIndicaPriceHLMA,
             IndiSetDeCateIndicaPriceCFTPP,
             IndiSetDeCateIndicaPriceDEMA,
             IndiSetDeCateIndicaPriceDemark,
             IndiSetDeCateIndicaPriceDetrend,
             IndiSetDeCateIndicaPriceEnvelope,
             IndiSetDeCateIndicaPriceIchimoku,
             IndiSetDeCateIndicaPriceMovingAverage,
             IndiSetDeCateIndicaPriceMAEnvelope,
             IndiSetDeCateIndicaPriceMedianPrices,
             IndiSetDeCateIndicaPricePivot,
             IndiSetDeCateIndicaPricePriceChannel,
             IndiSetDeCateIndicaPriceProjectionBand,
             IndiSetDeCateIndicaPricePSar,
             IndiSetDeCateIndicaPriceStdDevBands,
             IndiSetDeCateIndicaPriceTEMA,
             IndiSetDeCateIndicaPriceTypicalPrices,
             IndiSetDeCateIndicaPriceVIDYA,
             IndiSetDeCateIndicaPriceWeightedCloses,
             IndiSetDeCateIndicaPriceZigZag,
             IndiSetDeCateIndicaPricePriceMA,
             IndiSetDeCateIndicaPriceSMA,
             IndiSetDeCateIndicaPriceHighLowLine,
             IndiSetDeCateIndicaPriceMcginleyDynamic,
             IndiSetDeCateIndicaPriceMovingAverageChannels,
             IndiSetDeCateIndicaPriceLinearRegressionIndex,
             IndiSetDeCateIndicaPriceKeltnerChannels,
             IndiSetDeCateIndicaPriceCBO,
             IndiSetDeCateIndicaPricePriceHighLowIndex];
}


/// 지표 - 모멘텀지표- 58개
NSArray <NSString *>* AllCasesIndiSetDeCateIndicaMomentum(void) {
    return @[IndiSetDeCateIndicaMomentumAccumSwingIndex,
             IndiSetDeCateIndicaMomentumCCI,
             IndiSetDeCateIndicaMomentumChaikinOscillator,
             IndiSetDeCateIndicaMomentumROC,
             IndiSetDeCateIndicaMomentumDPO,
             IndiSetDeCateIndicaMomentumDX,
             IndiSetDeCateIndicaMomentumEnergyIndex,
             IndiSetDeCateIndicaMomentumErayBull,
             IndiSetDeCateIndicaMomentumErayBear,
             IndiSetDeCateIndicaMomentumIMI,
             IndiSetDeCateIndicaMomentumMACD,
             IndiSetDeCateIndicaMomentumMACDOscillator,
             IndiSetDeCateIndicaMomentumMassIndex,
             IndiSetDeCateIndicaMomentumMomentum,
             IndiSetDeCateIndicaMomentumNetChangeOscillator,
             IndiSetDeCateIndicaMomentumPriceOscillator,
             IndiSetDeCateIndicaMomentumPriceOSCPct,
             IndiSetDeCateIndicaMomentumProjectionBandwidth,
             IndiSetDeCateIndicaMomentumProjectionOscillator,
             IndiSetDeCateIndicaMomentumPVO,
             IndiSetDeCateIndicaMomentumPriceROC,
             IndiSetDeCateIndicaMomentumLinearRegressionSlope,
             IndiSetDeCateIndicaMomentumRMI,
             IndiSetDeCateIndicaMomentumRSI,
             IndiSetDeCateIndicaMomentumRWI,
             IndiSetDeCateIndicaMomentumStochasticFast,
             IndiSetDeCateIndicaMomentumStochasticSlow,
             IndiSetDeCateIndicaMomentumStochFastOsc,
             IndiSetDeCateIndicaMomentumStochRSI,
             IndiSetDeCateIndicaMomentumSwingIndex,
             IndiSetDeCateIndicaMomentumTSI,
             IndiSetDeCateIndicaMomentumUltimateOscillator,
             IndiSetDeCateIndicaMomentumVolumeROC,
             IndiSetDeCateIndicaMomentumWilliamsR,
             IndiSetDeCateIndicaMomentumBandB,
             IndiSetDeCateIndicaMomentumPriceChangeLine,
             IndiSetDeCateIndicaMomentumBPDLHiLo,
             IndiSetDeCateIndicaMomentumBPDLRSI,
             IndiSetDeCateIndicaMomentumBPDLTrendFilterRaw,
             IndiSetDeCateIndicaMomentumMorrisMixedMomentum,
             IndiSetDeCateIndicaMomentumMACDSAR,
             IndiSetDeCateIndicaMomentumOnBalancePrice,
             IndiSetDeCateIndicaMomentumArmsEaseOfMovement,
             IndiSetDeCateIndicaMomentumBandWidth,
             IndiSetDeCateIndicaMomentumEOM,
             IndiSetDeCateIndicaMomentumHighLowOscillator,
             IndiSetDeCateIndicaMomentumMorrisDailyPressure,
             IndiSetDeCateIndicaMomentumNorthPriceActionLine,
             IndiSetDeCateIndicaMomentumReverse,
             IndiSetDeCateIndicaMomentumVelocityIndex,
             IndiSetDeCateIndicaMomentumVolumeOscillator,
             IndiSetDeCateIndicaMomentumBostiansIntradayIntensityIndex,
             IndiSetDeCateIndicaMomentumBPDLShortTrend,
             IndiSetDeCateIndicaMomentumLinearRegressionConst,
             IndiSetDeCateIndicaMomentumROCN,
             IndiSetDeCateIndicaMomentumRSIOld,
             IndiSetDeCateIndicaMomentumVPCI,
             IndiSetDeCateIndicaMomentumVolumeWeightedAvgPrice];
}


/// 지표 - 변동성지표 - 19개
NSArray <NSString *>* AllCasesIndiSetDeCateIndicaVolatility(void) {
    return @[IndiSetDeCateIndicaVolatilityAverageTrueRange,
             IndiSetDeCateIndicaVolatilityBollingerWidth,
             IndiSetDeCateIndicaVolatilityChaikinVolatility,
             IndiSetDeCateIndicaVolatilityDiffRatio,
             IndiSetDeCateIndicaVolatilityDiffValue,
             IndiSetDeCateIndicaVolatilityDispersion,
             IndiSetDeCateIndicaVolatilityNeoPsychology,
             IndiSetDeCateIndicaVolatilityPerformancePct,
             IndiSetDeCateIndicaVolatilityRVI,
             IndiSetDeCateIndicaVolatilityStandardDeviation,
             IndiSetDeCateIndicaVolatilityStandardError,
             IndiSetDeCateIndicaVolatilityTrueRange,
             IndiSetDeCateIndicaVolatilityTrendScore,
             IndiSetDeCateIndicaVolatilityWellesSum,
             IndiSetDeCateIndicaVolatilityOpenDifference,
             IndiSetDeCateIndicaVolatilityVolumePriceInSync,
             IndiSetDeCateIndicaVolatilityABRatio,
             IndiSetDeCateIndicaVolatilityRVIoriginal,
             IndiSetDeCateIndicaVolatilityRelativeVigorIndex];
}


NSArray <NSString *>* AllCasesIndiSetDeCateIndicaChannel(void) {
    return @[IndiSetDeCateIndicaChannelAR,
             IndiSetDeCateIndicaChannelBOP,
             IndiSetDeCateIndicaChannelBR,
             IndiSetDeCateIndicaChannelCMO,
             IndiSetDeCateIndicaChannelMesaSineWave,
             IndiSetDeCateIndicaChannelNMO,
             IndiSetDeCateIndicaChannelRangeIndicator,
             IndiSetDeCateIndicaChannelSMI,
             IndiSetDeCateIndicaChannelEMV,
             IndiSetDeCateIndicaChannelBinaryWaveMACD];
}


/// 지표 - 추세지표 - 27개
NSArray <NSString *>* AllCasesIndiSetDeCateIndicaTrend(void) {
    return @[IndiSetDeCateIndicaTrendADX,
             IndiSetDeCateIndicaTrendADXR,
             IndiSetDeCateIndicaTrendAroon,
             IndiSetDeCateIndicaTrendAroonOSC,
             IndiSetDeCateIndicaTrendDMI,
             IndiSetDeCateIndicaTrendDynamicMI,
             IndiSetDeCateIndicaTrendForecastOscillator,
             IndiSetDeCateIndicaTrendMovingSum,
             IndiSetDeCateIndicaTrendPFE,
             IndiSetDeCateIndicaTrendQstickOscillator,
             IndiSetDeCateIndicaTrendSonarMomentum,
             IndiSetDeCateIndicaTrendT3,
             IndiSetDeCateIndicaTrendTRIX,
             IndiSetDeCateIndicaTrendVHF,
             IndiSetDeCateIndicaTrendAnnualPercentChange,
             IndiSetDeCateIndicaTrendBigMovesOnly,
             IndiSetDeCateIndicaTrendPringsKSTUserArithmetic,
             IndiSetDeCateIndicaTrendPringsLongKSTMonthly,
             IndiSetDeCateIndicaTrendPringsLongKSTWkly,
             IndiSetDeCateIndicaTrendPringsMedKSTWklyEMA,
             IndiSetDeCateIndicaTrendSmoothedROC,
             IndiSetDeCateIndicaTrendTrendex,
             IndiSetDeCateIndicaTrendTSF,
             IndiSetDeCateIndicaTrendMovingAverageOscillator,
             IndiSetDeCateIndicaTrendBWI,
             IndiSetDeCateIndicaTrendRankCorrelationIndex,
             IndiSetDeCateIndicaTrendStochasticSlowOSC];
}

/// 지표 - 시장강도지표 - 19개
NSArray <NSString *>* AllCasesIndiSetDeCateIndicaMarketStrength(void) {
    return @[IndiSetDeCateIndicaMarketStrengthAccumDistribution,
             IndiSetDeCateIndicaMarketStrengthBSI,
             IndiSetDeCateIndicaMarketStrengthCSIndex,
             IndiSetDeCateIndicaMarketStrengthDemandIndex,
             IndiSetDeCateIndicaMarketStrengthDownAverage,
             IndiSetDeCateIndicaMarketStrengthForceIndex,
             IndiSetDeCateIndicaMarketStrengthInertia,
             IndiSetDeCateIndicaMarketStrengthKlingerOscillator,
             IndiSetDeCateIndicaMarketStrengthMoneyFlowIndex,
             IndiSetDeCateIndicaMarketStrengthPsychologyIndex,
             IndiSetDeCateIndicaMarketStrengthOmegaIndex,
             IndiSetDeCateIndicaMarketStrengthInvestorPsychologyLine,
             IndiSetDeCateIndicaMarketStrengthPVRank,
             IndiSetDeCateIndicaMarketStrengthPVT,
             IndiSetDeCateIndicaMarketStrengthUpAverage,
             IndiSetDeCateIndicaMarketStrengthWilliamsAccumDist,
             IndiSetDeCateIndicaMarketStrengthBPDLStochastic,
             IndiSetDeCateIndicaMarketStrengthCompuTracVolatility,
             IndiSetDeCateIndicaMarketStrengthPluralityIndex];
}

/// 지표 - 거래량지표 - 27개
NSArray <NSString *>* AllCasesIndiSetDeCateIndicaVolume(void) {
    return @[IndiSetDeCateIndicaVolumeCMF,
             IndiSetDeCateIndicaVolumeMF,
             IndiSetDeCateIndicaVolumeNVI,
             IndiSetDeCateIndicaVolumeOBV,
             IndiSetDeCateIndicaVolumeOBVolMv,
             IndiSetDeCateIndicaVolumePVI,
             IndiSetDeCateIndicaVolumeVAO,
             IndiSetDeCateIndicaVolumeVolumeRatio,
             IndiSetDeCateIndicaVolumeVolume,
             IndiSetDeCateIndicaVolumeVolumeMA,
             IndiSetDeCateIndicaVolumeTradingVolume,
             IndiSetDeCateIndicaVolumeGMMMcClellanOsc,
             IndiSetDeCateIndicaVolumeGMMMcClellanSum,
             IndiSetDeCateIndicaVolumeBPDLMcClellanSum,
             IndiSetDeCateIndicaVolumeDailyVolumeIndex,
             IndiSetDeCateIndicaVolumeMorrisIntradayAcc,
             IndiSetDeCateIndicaVolumeMovingBalanceInd,
             IndiSetDeCateIndicaVolumeOBVwithAvgVol,
             IndiSetDeCateIndicaVolumeOBVMidpoint,
             IndiSetDeCateIndicaVolumeOBVOscillator,
             IndiSetDeCateIndicaVolumeSmoothAccumDist,
             IndiSetDeCateIndicaVolumeSpecialAccumDist,
             IndiSetDeCateIndicaVolumeDysartVolume,
             IndiSetDeCateIndicaVolumeVolPctPlusMinusAvg,
             IndiSetDeCateIndicaVolumeVolStdDev,
             IndiSetDeCateIndicaVolumeDailyAccumVolume,
             IndiSetDeCateIndicaVolumeDailyAccumTradingValue];
}

/// 지표 - 기타지표 - 19개
NSArray <NSString *>* AllCasesIndiSetDeCateIndicaOther(void) {
    return @[IndiSetDeCateIndicaOtherBinaryWave,
             IndiSetDeCateIndicaOtherPriceTradeCorrelation,
             IndiSetDeCateIndicaOtherPriceTradeCovariance,
             IndiSetDeCateIndicaOtherStochasticClose,
             IndiSetDeCateIndicaOtherWellesVolatilitySIC,
             IndiSetDeCateIndicaOtherWellesVolatilityARC,
             IndiSetDeCateIndicaOtherWellesVolatilitySAR,
             IndiSetDeCateIndicaOtherPriceTradeDecisionAnalysis,
             IndiSetDeCateIndicaOtherPriceTradeBetaAnalysis,
             IndiSetDeCateIndicaOtherHighLowEnvelope,
             IndiSetDeCateIndicaOtherLinearTrendOscillator,
             IndiSetDeCateIndicaOtherSigma,
             IndiSetDeCateIndicaOtherPriceSlope,
             IndiSetDeCateIndicaOtherVolumeSlope,
             IndiSetDeCateIndicaOtherSmoothedMomentum,
             IndiSetDeCateIndicaOtherStochasticFastClose,
             IndiSetDeCateIndicaOtherStochasticSlowClose,
             IndiSetDeCateIndicaOtherVolumePriceAccum,
             IndiSetDeCateIndicaOtherRSquared];
}

/// 신호 - 분석신호 - 126개
NSArray <NSString *>* AllCasesIndiSetDeCateSignAnal(void) {
    return @[IndiSetDeCateSignAnalEmaGoldenCross,
             IndiSetDeCateSignAnalEmaDeathCross,
             IndiSetDeCateSignAnalDisparityOverboughtEntry,
             IndiSetDeCateSignAnalDisparityOverboughtExit,
             IndiSetDeCateSignAnalDisparityOversoldExit,
             IndiSetDeCateSignAnalDisparityOversoldEntry,
             IndiSetDeCateSignAnalEmaPriceAboveCross,
             IndiSetDeCateSignAnalEmaPriceBelowCross,
             IndiSetDeCateSignAnalCmfOverboughtEntry,
             IndiSetDeCateSignAnalCmfOverboughtExit,
             IndiSetDeCateSignAnalCmfOversoldEntry,
             IndiSetDeCateSignAnalCmfOversoldExit,
             IndiSetDeCateSignAnalAroonDeathCross,
             IndiSetDeCateSignAnalAroonGoldenCross,
             IndiSetDeCateSignAnalCciOverboughtEntry,
             IndiSetDeCateSignAnalCciOverboughtExit,
             IndiSetDeCateSignAnalCciOversoldExit,
             IndiSetDeCateSignAnalCciOversoldEntry,
             IndiSetDeCateSignAnalDmiGoldenCross,
             IndiSetDeCateSignAnalDmiDeathCross,
             IndiSetDeCateSignAnalEiGoldenCross,
             IndiSetDeCateSignAnalEiDeathCross,
             IndiSetDeCateSignAnalCciThresholdUpwardBreak,
             IndiSetDeCateSignAnalCciThresholdDownwardBreak,
             IndiSetDeCateSignAnalMesaSineGoldenCross,
             IndiSetDeCateSignAnalMesaSineDeathCross,
             IndiSetDeCateSignAnalPsarPriceUpwardBreak,
             IndiSetDeCateSignAnalPsarPriceDownwardBreak,
             IndiSetDeCateSignAnalRsiOverboughtEntry,
             IndiSetDeCateSignAnalRsiOverboughtExit,
             IndiSetDeCateSignAnalRsiOversoldExit,
             IndiSetDeCateSignAnalRsiOversoldEntry,
             IndiSetDeCateSignAnalRwiBullishReversal,
             IndiSetDeCateSignAnalRwiBearishReversal,
             IndiSetDeCateSignAnalStochasticFastOverboughtExit,
             IndiSetDeCateSignAnalStochasticFastOverboughtEntry,
             IndiSetDeCateSignAnalStochasticFastOversoldExit,
             IndiSetDeCateSignAnalStochasticFastOversoldEntry,
             IndiSetDeCateSignAnalStochasticSlowOverboughtExit,
             IndiSetDeCateSignAnalStochasticSlowOverboughtEntry,
             IndiSetDeCateSignAnalStochasticSlowDivergenceEntry,
             IndiSetDeCateSignAnalStochasticSlowDivergenceExit,
             IndiSetDeCateSignAnalMacdThresholdCrossAbove,
             IndiSetDeCateSignAnalMacdThresholdCrossBelow,
             IndiSetDeCateSignAnalMomentumBullishReversal,
             IndiSetDeCateSignAnalMomentumBearishReversal,
             IndiSetDeCateSignAnalTrendScoreBullishReversal,
             IndiSetDeCateSignAnalTrendScoreBearishReversal,
             IndiSetDeCateSignAnalTrixThresholdCrossAbove,
             IndiSetDeCateSignAnalTrixThresholdCrossBelow,
             IndiSetDeCateSignAnalUpDownAvgGoldenCross,
             IndiSetDeCateSignAnalUpDownAvgDeathCross,
             IndiSetDeCateSignAnalWilliamsRBuyEntry,
             IndiSetDeCateSignAnalWilliamsRBuyExit,
             IndiSetDeCateSignAnalWilliamsRSellExit,
             IndiSetDeCateSignAnalWilliamsRSellEntry,
             IndiSetDeCateSignAnalZigzagBearishReversal,
             IndiSetDeCateSignAnalZigzagBullishReversal,
             IndiSetDeCateSignAnalBollingerBandUpperBreakout,
             IndiSetDeCateSignAnalBollingerBandLowerBreakout,
             IndiSetDeCateSignAnalStochasticFastDeathCross,
             IndiSetDeCateSignAnalStochasticFastGoldenCross,
             IndiSetDeCateSignAnalDisparityGoldenCross,
             IndiSetDeCateSignAnalDisparityDeathCross,
             IndiSetDeCateSignAnalContinuousPriceRise,
             IndiSetDeCateSignAnalContinuousPriceFall,
             IndiSetDeCateSignAnalBinaryWaveBuySignal,
             IndiSetDeCateSignAnalDiPlusCrossesAboveDIMinus,
             IndiSetDeCateSignAnalDiPlusCrossesBelowDIMinus,
             IndiSetDeCateSignAnalEomSignalLineCrossesAbove,
             IndiSetDeCateSignAnalEomSignalLineCrossesBelow,
             IndiSetDeCateSignAnalMfiOverboughtZoneEntry,
             IndiSetDeCateSignAnalMfiOverboughtZoneExit,
             IndiSetDeCateSignAnalTrixSignalGoldenCross,
             IndiSetDeCateSignAnalTrixSignalDeathCross,
             IndiSetDeCateSignAnalMacdSignalGoldenCross,
             IndiSetDeCateSignAnalMacdSignalDeathCross,
             IndiSetDeCateSignAnalMfiOversoldZoneEntry,
             IndiSetDeCateSignAnalMfiOversoldZoneExit,
             IndiSetDeCateSignAnalIchimokuCloudEntry,
             IndiSetDeCateSignAnalIchimokuCloudExit,
             IndiSetDeCateSignAnalIchimokuCloudInside,
             IndiSetDeCateSignAnalIchimokuBaseLineLeadingSpan1CrossAbove,
             IndiSetDeCateSignAnalIchimokuBaseLineLeadingSpan1CrossBelow,
             IndiSetDeCateSignAnalIchimokuBaseLineLeadingSpan2CrossAbove,
             IndiSetDeCateSignAnalIchimokuBaseLineLeadingSpan2CrossBelow,
             IndiSetDeCateSignAnalIchimokuLeadingSpan12GoldenCross,
             IndiSetDeCateSignAnalIchimokuLeadingSpan12DeathCross,
             IndiSetDeCateSignAnalIchimokuConversionLineLeadingSpan1CrossAbove,
             IndiSetDeCateSignAnalIchimokuConversionLineLeadingSpan1CrossBelow,
             IndiSetDeCateSignAnalIchimokuConversionLineLeadingSpan2CrossAbove,
             IndiSetDeCateSignAnalIchimokuConversionLineLeadingSpan2CrossBelow,
             IndiSetDeCateSignAnalPriceRateOfChangeContinousNDays,
             IndiSetDeCateSignAnalPriceDecline,
             IndiSetDeCateSignAnalPriceAdvance,
             IndiSetDeCateSignAnalAverageVolumeOverNPeriodsMWeeks,
             IndiSetDeCateSignAnalVolumeDecline,
             IndiSetDeCateSignAnalVolumeAdvance,
             IndiSetDeCateSignAnalVolumeHighRenewal,
             IndiSetDeCateSignAnalVolumeLowRenewal,
             IndiSetDeCateSignAnalPeriodHigh,
             IndiSetDeCateSignAnalPeriodLow,
             IndiSetDeCateSignAnalNoTradingStock,
             IndiSetDeCateSignAnalNewHigh,
             IndiSetDeCateSignAnalNewLow,
             IndiSetDeCateSignAnalMovingAverageUpturn,
             IndiSetDeCateSignAnalMovingAverageDownturn,
             IndiSetDeCateSignAnalMovingAverageSupportLineNear,
             IndiSetDeCateSignAnalMovingAverageResistanceLineNear,
             IndiSetDeCateSignAnalMovingAverageConvergence,
             IndiSetDeCateSignAnalMovingAverageConvergenceUptrend,
             IndiSetDeCateSignAnalMovingAverageConvergenceDowntrend,
             IndiSetDeCateSignAnalPriceSideways,
             IndiSetDeCateSignAnalPriceSidewaysUptrend,
             IndiSetDeCateSignAnalPriceSidewaysDowntrend,
             IndiSetDeCateSignAnalPriceMovingAverageConvergence,
             IndiSetDeCateSignAnalPriceMovingAverageInverted,
             IndiSetDeCateSignAnalPriceMovingAverageRegular,
             IndiSetDeCateSignAnalObvSignalGoldenCross,
             IndiSetDeCateSignAnalObvSignalDeathCross,
             IndiSetDeCateSignAnalCeilingPrice,
             IndiSetDeCateSignAnalFloorPrice,
             IndiSetDeCateSignAnalStochasticSlowGoldenCross,
             IndiSetDeCateSignAnalStochasticSlowDeathCross,
             IndiSetDeCateSignAnalEilingPrice30Percent,
             IndiSetDeCateSignAnalLoorPrice30Percent];
}

/// 신호 - 매매신호 - 32개
NSArray <NSString *>* AllCasesIndiSetDeCateSignTrading(void) {
    return @[IndiSetDeCateSignTradingInsideDayBuy,
             IndiSetDeCateSignTradingInsideDaySell,
             IndiSetDeCateSignTradingPlan7percentBuy,
             IndiSetDeCateSignTradingPlan7percentSell,
             IndiSetDeCateSignTradingBuy180s,
             IndiSetDeCateSignTradingSell180s,
             IndiSetDeCateSignTradingGilligansIslandBuy,
             IndiSetDeCateSignTradingGilligansIslandSell,
             IndiSetDeCateSignTradingLizardsBuy,
             IndiSetDeCateSignTradingLizardsSell,
             IndiSetDeCateSignTradingOops10PercentBuy,
             IndiSetDeCateSignTradingOops10PercentSell,
             IndiSetDeCateSignTradingSlingShotsBuy,
             IndiSetDeCateSignTradingSlingShotsSell,
             IndiSetDeCateSignTradingSpentMarketTradingPatternBuy,
             IndiSetDeCateSignTradingSpentMarketTradingPatternSell,
             IndiSetDeCateSignTradingExtendedLevelBoomersBuy,
             IndiSetDeCateSignTradingExtendedLevelBoomersSell,
             IndiSetDeCateSignTradingPivotPointBuy,
             IndiSetDeCateSignTradingPivotPointSell,
             IndiSetDeCateSignTradingOutsideDayBuy,
             IndiSetDeCateSignTradingOutsideDaySell,
             IndiSetDeCateSignTradingOneTwoThreeFourBuy,
             IndiSetDeCateSignTradingOneTwoThreeFourSell,
             IndiSetDeCateSignTradingExpansionPivotsBuy,
             IndiSetDeCateSignTradingExpansionPivotsSell,
             IndiSetDeCateSignTradingBoomersBuy,
             IndiSetDeCateSignTradingBoomersSell,
             IndiSetDeCateSignTradingAdxGapperBuy,
             IndiSetDeCateSignTradingAdxGapperSell,
             IndiSetDeCateSignTradingJackInTheBoxStrategyBuy,
             IndiSetDeCateSignTradingJackInTheBoxStrategySell];
}


/// 패턴 - 상승반전패턴 - 27개
NSArray <NSString *>* AllCasesIndiSetDeCatePatBulRever(void) {
    return @[IndiSetDeCatePatBulReverBullishHammer,
             IndiSetDeCatePatBulReverBullishInvertedHammer,
             IndiSetDeCatePatBulReverPiercingPattern,
             IndiSetDeCatePatBulReverIdenticalLows,
             IndiSetDeCatePatBulReverIdenticalThreeCrows,
             IndiSetDeCatePatBulReverBullishEngulfing,
             IndiSetDeCatePatBulReverLadderBottom,
             IndiSetDeCatePatBulReverRisingSunDoji,
             IndiSetDeCatePatBulReverRisingFallingThreeMethods,
             IndiSetDeCatePatBulReverBullishCounterattack,
             IndiSetDeCatePatBulReverBullishKicker,
             IndiSetDeCatePatBulReverBullishThreeWhiteSoldiers,
             IndiSetDeCatePatBulReverBullishStalledPattern,
             IndiSetDeCatePatBulReverBullishKickback,
             IndiSetDeCatePatBulReverBullishConfirmedKickback,
             IndiSetDeCatePatBulReverBullishEngulfingHarami,
             IndiSetDeCatePatBulReverBullishConfirmedEngulfingHarami,
             IndiSetDeCatePatBulReverBullishEscape,
             IndiSetDeCatePatBulReverMorningStar,
             IndiSetDeCatePatBulReverBullishMorningDojiStar,
             IndiSetDeCatePatBulReverBabySwallow,
             IndiSetDeCatePatBulReverBullishThreeLineStrike,
             IndiSetDeCatePatBulReverBullishHammerInvertedHammer,
             IndiSetDeCatePatBulReverBearishThreeBlackCrows,
             IndiSetDeCatePatBulReverMorningDojiStar,
             IndiSetDeCatePatBulReverTweezerBottom,
             IndiSetDeCatePatBulReverRareThreeRiverBottom];
}

/// 패턴 - 상승지속패턴 - 10개
NSArray <NSString *>* AllCasesIndiSetDeCatePatBullConti(void) {
    return @[IndiSetDeCatePatBullContiBullishThreeLineStrike,
             IndiSetDeCatePatBullContiMatHold,
             IndiSetDeCatePatBullContiBlockPattern,
             IndiSetDeCatePatBullContiBullishFork,
             IndiSetDeCatePatBullContiBullishGapThreeMethods,
             IndiSetDeCatePatBullContiBullishSideBySideWhiteLines,
             IndiSetDeCatePatBullContiBullishThreeMethods,
             IndiSetDeCatePatBullContiBullishTasukiGap,
             IndiSetDeCatePatBullContiBullishLongWhiteCandle,
             IndiSetDeCatePatBullContiDelayedPattern];
}

/// 패턴 - 하락반전패턴 - 24개
NSArray <NSString *>* AllCasesIndiSetDeCatePatBearRever(void) {
    return @[IndiSetDeCatePatBearReverProfessorPattern,
             IndiSetDeCatePatBearReverSouthernStar,
             IndiSetDeCatePatBearReverCrowPattern,
             IndiSetDeCatePatBearReverHammerPattern,
             IndiSetDeCatePatBearReverStoneStar,
             IndiSetDeCatePatBearReverCrossStoneStar,
             IndiSetDeCatePatBearReverWeakCrowPattern,
             IndiSetDeCatePatBearReverWeakStonePattern,
             IndiSetDeCatePatBearReverWeakInvertedHammer,
             IndiSetDeCatePatBearReverShootingStar,
             IndiSetDeCatePatBearReverTweezerTop,
             IndiSetDeCatePatBearReverBearishAbandonedBaby,
             IndiSetDeCatePatBearReverBearishFallingThreeMethods,
             IndiSetDeCatePatBearReverBearishCounterattack,
             IndiSetDeCatePatBearReverBearishKicker,
             IndiSetDeCatePatBearReverBearishThreeBlackCrows,
             IndiSetDeCatePatBearReverBearishStalledPattern,
             IndiSetDeCatePatBearReverBearishKickback,
             IndiSetDeCatePatBearReverBearishConfirmedKickback,
             IndiSetDeCatePatBearReverBearishEngulfingHarami,
             IndiSetDeCatePatBearReverBearishConfirmedEngulfingHarami,
             IndiSetDeCatePatBearReverBearishEscape,
             IndiSetDeCatePatBearReverBlackThreeCrows,
             IndiSetDeCatePatBearReverBlackCloudCover];
}

/// 패턴 - 하락지속패턴 - 9개
NSArray <NSString *>* AllCasesIndiSetDeCatePatBearConti(void) {
    return @[IndiSetDeCatePatBearContiThrustingLine,
             IndiSetDeCatePatBearContiCrossingLine,
             IndiSetDeCatePatBearContiLongBlackCandle,
             IndiSetDeCatePatBearContiEntryPattern,
             IndiSetDeCatePatBearContiBearishFork,
             IndiSetDeCatePatBearContiBearishGapThreeMethods,
             IndiSetDeCatePatBearContiBearishSideBySidePattern,
             IndiSetDeCatePatBearContiBearishThreeMethods,
             IndiSetDeCatePatBearContiBearishTasukiGap];
}

/// 패턴 - 추세패턴 - 46개
NSArray <NSString *>* AllCasesIndiSetDeCatePatTrend(void) {
    return @[IndiSetDeCatePatTrendAttemptedRecoveryAfter2Declines,
             IndiSetDeCatePatTrendConsecutiveRises2,
             IndiSetDeCatePatTrendConsecutiveDeclines2,
             IndiSetDeCatePatTrendAttemptedRecoveryAfter3Declines,
             IndiSetDeCatePatTrendConsecutiveRises3,
             IndiSetDeCatePatTrendConsecutiveDeclines3,
             IndiSetDeCatePatTrendConsecutiveRises4,
             IndiSetDeCatePatTrendConsecutiveDeclines4,
             IndiSetDeCatePatTrendMPattern,
             IndiSetDeCatePatTrendTwinPeaksPattern,
             IndiSetDeCatePatTrendVBottomPattern,
             IndiSetDeCatePatTrendAsymmetricVBottomPattern,
             IndiSetDeCatePatTrendExpandedVBottomPattern,
             IndiSetDeCatePatTrendVTopPattern,
             IndiSetDeCatePatTrendExpandedVTopPattern,
             IndiSetDeCatePatTrendAsymmetricVTopPattern,
             IndiSetDeCatePatTrendExpandedAsymmetricVBottomPattern,
             IndiSetDeCatePatTrendExpandedAsymmetricVTopPattern,
             IndiSetDeCatePatTrendWPattern,
             IndiSetDeCatePatTrendInvertedTwinPeaksPattern,
             IndiSetDeCatePatTrendBullishAscendingTriangle,
             IndiSetDeCatePatTrendHeadAndShouldersPattern,
             IndiSetDeCatePatTrendFailedRally,
             IndiSetDeCatePatTrendBullishFlag,
             IndiSetDeCatePatTrendBullishRectangle,
             IndiSetDeCatePatTrendBullishConsolidationThenBearish,
             IndiSetDeCatePatTrendBullishAfter2ConsecutiveDeclines,
             IndiSetDeCatePatTrendBearishDescendingTriangle,
             IndiSetDeCatePatTrendInvertedHeadAndShouldersPattern,
             IndiSetDeCatePatTrendDoubleBottomPattern,
             IndiSetDeCatePatTrendDoubleTopPattern,
             IndiSetDeCatePatTrendSidewaysAdjustmentThen2Rises,
             IndiSetDeCatePatTrendSidewaysConsolidationThenBullish,
             IndiSetDeCatePatTrendRecoveryAfterCorrection,
             IndiSetDeCatePatTrendBearishRectangle,
             IndiSetDeCatePatTrendBullishConsolidationThenRise,
             IndiSetDeCatePatTrendBullishAfter2ConsecutiveRises,
             IndiSetDeCatePatTrendExpandedTriangle,
             IndiSetDeCatePatTrendSidewaysConsolidationThen2Rises,
             IndiSetDeCatePatTrendSidewaysConsolidationThen2Declines,
             IndiSetDeCatePatTrendSidewaysConsolidationThenRise,
             IndiSetDeCatePatTrendBullishConsolidationThenRecovery,
             IndiSetDeCatePatTrendBearishConsolidationThenSharpDecline,
             IndiSetDeCatePatTrendSidewaysConsolidationThenDecline,
             IndiSetDeCatePatTrendRecoveryAfterSharpDecline,
             IndiSetDeCatePatTrendFailedBreakdown];
}

/// 구간 74개
NSArray <NSString *>* AllCasesIndiSetDeCateRange(void) {
    return @[IndiSetDeCateRangeOverbought,
             IndiSetDeCateRangeOversold,
             IndiSetDeCateRangeStrongTrendBetweenMovingAverages,
             IndiSetDeCateRangeWeakTrendBetweenMovingAverages,
             IndiSetDeCateRangeStrongTrendBetweenPriceAndMovingAverages,
             IndiSetDeCateRangeWeakTrendBetweenPriceAndMovingAverages,
             IndiSetDeCateRangeOverboughtInvestorSentiment,
             IndiSetDeCateRangeOversoldInvestorSentiment,
             IndiSetDeCateRangeStrongAroon,
             IndiSetDeCateRangeWeakAroon,
             IndiSetDeCateRangeOverboughtCCI,
             IndiSetDeCateRangeOversoldCCI,
             IndiSetDeCateRangeStrongDMI,
             IndiSetDeCateRangeWeakDMI,
             IndiSetDeCateRangeStrongMACDLine,
             IndiSetDeCateRangeWeakMACDLine,
             IndiSetDeCateRangeBullishMACDCrossover,
             IndiSetDeCateRangeBearishMACDCrossover,
             IndiSetDeCateRangeStrongMomentum,
             IndiSetDeCateRangeWeakMomentum,
             IndiSetDeCateRangeWeakMomentumBaseline,
             IndiSetDeCateRangeStrongMomentumBaseline,
             IndiSetDeCateRangeStrongParabolicSAR,
             IndiSetDeCateRangeWeakParabolicSAR,
             IndiSetDeCateRangeOverboughtRSI,
             IndiSetDeCateRangeOversoldRSI,
             IndiSetDeCateRangeStrongRSI,
             IndiSetDeCateRangeWeakRSI,
             IndiSetDeCateRangeStrongTRIX,
             IndiSetDeCateRangeWeakTRIX,
             IndiSetDeCateRangeStrongTRIXBaseline,
             IndiSetDeCateRangeWeakTRIXBaseline,
             IndiSetDeCateRangeStrongADXBaseline,
             IndiSetDeCateRangeWeakADXBaseline,
             IndiSetDeCateRangeStrongEnergyIndex,
             IndiSetDeCateRangeWeakEnergyIndex,
             IndiSetDeCateRangeStrongMesaSineWave,
             IndiSetDeCateRangeWeakMesaSineWave,
             IndiSetDeCateRangeStrongRWI,
             IndiSetDeCateRangeWeakRWI,
             IndiSetDeCateRangeBullishZigZag,
             IndiSetDeCateRangeBearishZigZag,
             IndiSetDeCateRangeOverboughtWilliamsR,
             IndiSetDeCateRangeOversoldWilliamsR,
             IndiSetDeCateRangeStrongUpDownAVG,
             IndiSetDeCateRangeWeakUpDownAVG,
             IndiSetDeCateRangeStrongTrendScore,
             IndiSetDeCateRangeWeakTrendScore,
             IndiSetDeCateRangeStrongStochasticFast,
             IndiSetDeCateRangeWeakStochasticFast,
             IndiSetDeCateRangeStrongStochasticSlow,
             IndiSetDeCateRangeWeakStochasticSlow,
             IndiSetDeCateRangeStrongABRatio,
             IndiSetDeCateRangeWeakABRatio,
             IndiSetDeCateRangeStrongBinaryWave,
             IndiSetDeCateRangeWeakBinaryWave,
             IndiSetDeCateRangeOverboughtChaikinsOscillator,
             IndiSetDeCateRangeOversoldChaikinsOscillator,
             IndiSetDeCateRangeStrongEOM,
             IndiSetDeCateRangeWeakEOM,
             IndiSetDeCateRangeStrongNetChangeOscillator,
             IndiSetDeCateRangeWeakNetChangeOscillator,
             IndiSetDeCateRangeStrongNVI,
             IndiSetDeCateRangeWeakNVI,
             IndiSetDeCateRangeStrongPVI,
             IndiSetDeCateRangeWeakPVI,
             IndiSetDeCateRangeStrongPriceROC,
             IndiSetDeCateRangeWeakPriceROC,
             IndiSetDeCateRangeStrongSonar,
             IndiSetDeCateRangeWeakSonar,
             IndiSetDeCateRangeStrongVR,
             IndiSetDeCateRangeWeakVR,
             IndiSetDeCateRangeOverboughtMFI,
             IndiSetDeCateRangeOversoldMFI];
}

/// 채움 - 가격영역채움 - 28개
NSArray <NSString *>* AllCasesIndiSetDeCateFillPrice(void) {
    return @[IndiSetDeCateFillPriceBollingerBand,
             IndiSetDeCateFillPriceCFTPPFirst,
             IndiSetDeCateFillPriceCFTPPSecond,
             IndiSetDeCateFillPriceDema,
             IndiSetDeCateFillPriceEnvelope,
             IndiSetDeCateFillPricePriceMovingAverage,
             IndiSetDeCateFillPricePriceMovingAverageBetween,
             IndiSetDeCateFillPricePriceChannel,
             IndiSetDeCateFillPricePriceHighLow,
             IndiSetDeCateFillPriceProjectionBand,
             IndiSetDeCateFillPricePsar,
             IndiSetDeCateFillPriceTema,
             IndiSetDeCateFillPriceVidya,
             IndiSetDeCateFillPriceZigzag,
             IndiSetDeCateFillPriceHighLow,
             IndiSetDeCateFillPriceIchimokuConversionLine,
             IndiSetDeCateFillPriceIchimokuBaseLine,
             IndiSetDeCateFillPriceIchimokuLeadingSpanA,
             IndiSetDeCateFillPriceStandardDeviationBands,
             IndiSetDeCateFillPriceMovingAverageHighestLowest,
             IndiSetDeCateFillPriceMovingAverageUpperLower,
             IndiSetDeCateFillPriceMaEnvelope,
             IndiSetDeCateFillPriceLinearRegIndexSignal,
             IndiSetDeCateFillPriceCBO,
             IndiSetDeCateFillPriceKeltnerChannels,
             IndiSetDeCateFillPricePivotFirst,
             IndiSetDeCateFillPricePivotSecond,
             IndiSetDeCateFillPriceDemark];
}


/// 채움 - 거래량영역채움 - 2개
NSArray <NSString *>* AllCasesIndiSetDeCateFillVolume(void) {
    return @[IndiSetDeCateFillVolumeMovingAverageBetween,
             IndiSetDeCateFillVolumeMovingAverage];
}

/// 채움 - 분석영역채움 - 22개
NSArray <NSString *>* AllCasesIndiSetDeCateFillAnal(void) {
    return @[IndiSetDeCateFillAnalAroon,
             IndiSetDeCateFillAnalCCISignal,
             IndiSetDeCateFillAnalElerRay,
             IndiSetDeCateFillAnalMacdSignal,
             IndiSetDeCateFillAnalReverse,
             IndiSetDeCateFillAnalRSI,
             IndiSetDeCateFillAnalRsiSignal,
             IndiSetDeCateFillAnalStochasticFast,
             IndiSetDeCateFillAnalStochasticSlow,
             IndiSetDeCateFillAnalDivergenceBetween,
             IndiSetDeCateFillAnalAbRatio,
             IndiSetDeCateFillAnalOpenDifference,
             IndiSetDeCateFillAnalRelativeVigorIndex,
             IndiSetDeCateFillAnalEnergyIndex,
             IndiSetDeCateFillAnalErayBullBear,
             IndiSetDeCateFillAnalRWI,
             IndiSetDeCateFillAnalArBr,
             IndiSetDeCateFillAnalMesaSineWave,
             IndiSetDeCateFillAnalDMI,
             IndiSetDeCateFillAnalRankCorrelationIndex,
             IndiSetDeCateFillAnalUpDownAverage,
             IndiSetDeCateFillAnalPviNvi];
}

//@implementation IndicatorSettingViewModel (Enum)
//
//@end
